"""End-of-season summary display (Phase 4 Prompt #9).

Renders after each season completes. Pulls from:
- legacy.py (legacy scores)
- peer_ranking.py (active/all-time rank)
- narrative_beats.py (season narrative)
- owner_sentiment.py (sentiment trajectory + hot seat)
- historical_records.py (records broken this season)
- press_conference.py + tier2_press_conference.py (press summary)
"""

import sqlite3
from typing import Optional
from src.utils.constants import (
    DISPLAY_WIDTH, DISPLAY_BORDER_HEAVY, DISPLAY_BORDER_LIGHT,
    SEASON_SUMMARY_SECTIONS, REGULAR_SEASON_WEEKS,
)
from src.ui.colors import bold, dim, cyan, yellow, green, red
from src.db.queries import (
    get_owner_sentiment,
    get_peer_ranking,
    get_narrative_beats_for_coach,
    get_coach_legacy_scores,
)


def render_season_summary(
    conn: sqlite3.Connection,
    season_year: int,
    coach_id: int,
    use_color: bool = True,
) -> str:
    """Compose full end-of-season summary as printable string."""
    sections = []
    for section_name in SEASON_SUMMARY_SECTIONS:
        renderer = SECTION_RENDERERS[section_name]
        section_text = renderer(conn, season_year, coach_id, use_color)
        if section_text:
            sections.append(section_text)
    return '\n\n'.join(sections)


def render_header(conn, season_year, coach_id, use_color):
    """SEASON 2026 - COMPLETE  •  CHICAGO CARDINALS  10-7"""
    # Get team info
    coach = conn.execute("""
        SELECT ct.current_team_id
        FROM coach_career ct
        WHERE ct.id = ?
    """, (coach_id,)).fetchone()

    if not coach or not coach['current_team_id']:
        return ""

    team_id = coach['current_team_id']

    # Get team name and record
    team_row = conn.execute("""
        SELECT t.city, t.nickname
        FROM team t
        WHERE t.id = ?
    """, (team_id,)).fetchone()

    if not team_row:
        return ""

    # Get record from team_season_record
    standings = conn.execute("""
        SELECT wins, losses
        FROM team_season_record
        WHERE season_year = ? AND team_id = ?
    """, (season_year, team_id)).fetchone()

    if not standings:
        wins, losses = 0, 0
    else:
        wins, losses = standings['wins'], standings['losses']

    team_name = f"{team_row['city']} {team_row['nickname']}".upper()
    record = f"{wins}-{losses}"

    header = f"SEASON {season_year} - COMPLETE  •  {team_name}  {record}"
    return bold(header, use_color)


def render_outcome(conn, season_year, coach_id, use_color):
    """One-line: 'Super Bowl Champions' (green) | 'Made Playoffs' (yellow) | 'Missed Playoffs' (red)"""
    # Get team ID
    coach = conn.execute("""
        SELECT ct.current_team_id
        FROM coach_career ct
        WHERE ct.id = ?
    """, (coach_id,)).fetchone()

    if not coach or not coach['current_team_id']:
        return ""

    team_id = coach['current_team_id']

    # Check if champion
    season_row = conn.execute("""
        SELECT champion_team_id
        FROM season
        WHERE year = ?
    """, (season_year,)).fetchone()

    if season_row and season_row['champion_team_id'] == team_id:
        return green("★ SUPER BOWL CHAMPIONS ★", use_color)

    # Check if made playoffs (games in weeks after regular season)
    playoff_game = conn.execute("""
        SELECT 1
        FROM game g
        JOIN week w ON g.week_id = w.id
        JOIN season s ON w.season_id = s.id
        WHERE s.year = ? AND w.week_number > ?
          AND (g.home_team_id = ? OR g.away_team_id = ?)
        LIMIT 1
    """, (season_year, REGULAR_SEASON_WEEKS, team_id, team_id)).fetchone()

    if playoff_game:
        return yellow("Made Playoffs", use_color)
    else:
        return red("Missed Playoffs", use_color)


def render_narrative(conn, season_year, coach_id, use_color):
    """Section: THE STORY OF YOUR SEASON
    Pulls from coach_narrative_beat.text (already generated by Prompt #7).
    Indented quote block."""
    beats = get_narrative_beats_for_coach(conn, coach_id)

    # Filter to this season
    season_beats = [b for b in beats if b['season_year'] == season_year]

    if not season_beats:
        return ""

    lines = [bold("THE STORY OF YOUR SEASON", use_color), DISPLAY_BORDER_LIGHT]

    for beat in season_beats:
        # Indent the narrative text
        text = beat['text']
        lines.append(f"  {text}")

    return '\n'.join(lines)


def render_owner_relationship(conn, season_year, coach_id, use_color):
    """Section: OWNER RELATIONSHIP
    - Sentiment trajectory (start → end with delta)
    - Hot seat tier next season
    - Expectation vs actual
    Pull from owner_sentiment."""
    # Get team ID
    coach = conn.execute("""
        SELECT ct.current_team_id
        FROM coach_career ct
        WHERE ct.id = ?
    """, (coach_id,)).fetchone()

    if not coach or not coach['current_team_id']:
        return ""

    team_id = coach['current_team_id']

    sentiment = get_owner_sentiment(conn, team_id, season_year)

    if not sentiment:
        return ""

    lines = [bold("OWNER RELATIONSHIP", use_color), DISPLAY_BORDER_LIGHT]

    # Sentiment score
    sentiment_score = sentiment['sentiment_score']
    lines.append(f"  Sentiment:  {sentiment_score}")

    # Hot seat tier
    hot_seat = sentiment['hot_seat_tier']
    if hot_seat == 'safe' or hot_seat == 'stable':
        hot_seat_display = green("Safe", use_color)
    elif hot_seat == 'warm':
        hot_seat_display = yellow("Warm", use_color)
    elif hot_seat == 'hot':
        hot_seat_display = red("Hot", use_color)
    elif hot_seat == 'urgent':
        hot_seat_display = bold(red("URGENT", use_color), use_color)
    else:
        hot_seat_display = hot_seat

    lines.append(f"  Hot seat:   {hot_seat_display}")

    # Expectation and wins vs expectation
    expectation = sentiment['preseason_expectation']
    wins_vs_exp = sentiment['wins_vs_expectation']

    if expectation:
        exp_display = expectation.replace('_', ' ').title()
        if wins_vs_exp > 0:
            vs_str = green(f"+{wins_vs_exp} vs expectation ({exp_display})", use_color)
        elif wins_vs_exp < 0:
            vs_str = red(f"{wins_vs_exp} vs expectation ({exp_display})", use_color)
        else:
            vs_str = f"Met expectation ({exp_display})"
        lines.append(f"  Performance: {vs_str}")

    return '\n'.join(lines)


def render_legacy_update(conn, season_year, coach_id, use_color):
    """Section: LEGACY UPDATE
    - Season contribution (show multipliers)
    - Career legacy total + delta from previous season
    Pull from legacy_score (aggregate) and coach_legacy_score (per-season detail)."""
    # Get aggregate legacy score for this season
    legacy_agg = conn.execute("""
        SELECT total_legacy_score, is_dynasty, hof_eligible
        FROM legacy_score
        WHERE season_year = ? AND coach_id = ?
    """, (season_year, coach_id)).fetchone()

    if not legacy_agg:
        return ""

    # Get per-season detail
    season_detail = conn.execute("""
        SELECT season_legacy_score, era_difficulty_multiplier, starting_condition_multiplier
        FROM coach_legacy_score
        WHERE season_year = ? AND coach_id = ?
    """, (season_year, coach_id)).fetchone()

    if not season_detail:
        return ""

    lines = [bold("LEGACY UPDATE", use_color), DISPLAY_BORDER_LIGHT]

    # Season contribution
    season_score = season_detail['season_legacy_score']
    lines.append(f"  This season:        {season_score:+d}")

    # Multipliers
    era_mult = season_detail['era_difficulty_multiplier']
    cond_mult = season_detail['starting_condition_multiplier']
    if era_mult != 1.0 or cond_mult != 1.0:
        lines.append(f"    Era difficulty:   {era_mult:.2f}x")
        lines.append(f"    Starting cond:    {cond_mult:.2f}x")

    # Career total
    career_total = legacy_agg['total_legacy_score']

    # Get previous season for delta
    prev_legacy = conn.execute("""
        SELECT total_legacy_score
        FROM legacy_score
        WHERE season_year = ? AND coach_id = ?
    """, (season_year - 1, coach_id)).fetchone()

    if prev_legacy:
        prev_total = prev_legacy['total_legacy_score']
        delta = career_total - prev_total
        if delta > 0:
            delta_str = green(f"+{delta}", use_color)
        else:
            delta_str = red(f"{delta}", use_color)
        lines.append(f"  Career legacy:      {career_total}  ({delta_str})")
    else:
        lines.append(f"  Career legacy:      {career_total}")

    # Dynasty/HOF flags
    if legacy_agg['is_dynasty']:
        lines.append(bold(green("  ★ DYNASTY COACH", use_color), use_color))

    if legacy_agg['hof_eligible']:
        lines.append(bold(cyan("  ★ HALL OF FAME ELIGIBLE", use_color), use_color))

    return '\n'.join(lines)


def render_peer_rank(conn, season_year, coach_id, use_color):
    """Section: PEER RANK
    - Active rank: #X of N
    - All-time rank: #Y of M
    - Trajectory hint (up/down from last season)
    Pull from peer_ranking_snapshot."""
    ranking = get_peer_ranking(conn, coach_id, season_year)

    if not ranking:
        return ""

    lines = [bold("PEER RANK", use_color), DISPLAY_BORDER_LIGHT]

    active_rank = ranking['active_rank']
    n_active = ranking['n_active']
    all_time_rank = ranking['all_time_rank']
    n_all_time = ranking['n_all_time']

    lines.append(f"  Active:    #{active_rank} of {n_active}")
    lines.append(f"  All-time:  #{all_time_rank} of {n_all_time}")

    # Trajectory (compare to previous season)
    prev_ranking = get_peer_ranking(conn, coach_id, season_year - 1)
    if prev_ranking:
        prev_active = prev_ranking['active_rank']
        if active_rank < prev_active:
            lines.append(green(f"  ↑ Moved up {prev_active - active_rank} spots", use_color))
        elif active_rank > prev_active:
            lines.append(red(f"  ↓ Fell {active_rank - prev_active} spots", use_color))

    return '\n'.join(lines)


def render_records_broken(conn, season_year, coach_id, use_color):
    """Section: RECORDS BROKEN
    List any league_record entries updated this season AND held by
    a player on this coach's team. Empty section returns ''."""
    # Get team ID
    coach = conn.execute("""
        SELECT ct.current_team_id
        FROM coach_career ct
        WHERE ct.id = ?
    """, (coach_id,)).fetchone()

    if not coach or not coach['current_team_id']:
        return ""

    team_id = coach['current_team_id']

    # Find records set this season by players on this team
    records = conn.execute("""
        SELECT lr.category, lr.scope, lr.record_value, lr.holder_name
        FROM league_record lr
        WHERE lr.season_year = ?
          AND lr.holder_team_id = ?
        ORDER BY lr.set_at DESC
        LIMIT 10
    """, (season_year, team_id)).fetchall()

    if not records:
        return ""

    lines = [bold("RECORDS BROKEN", use_color), DISPLAY_BORDER_LIGHT]

    for record in records:
        category = record['category'].replace('_', ' ').title()
        scope = record['scope'].replace('_', ' ').title()
        value = record['record_value']
        holder = record['holder_name']

        # Format value (handle REAL for sacks)
        if isinstance(value, float) and value % 1 != 0:
            value_str = f"{value:.1f}"
        else:
            value_str = f"{int(value)}"

        lines.append(f"  {holder}: {category} ({scope}) — {value_str}")

    return '\n'.join(lines)


def render_press_summary(conn, season_year, coach_id, use_color):
    """Section: PRESS CONFERENCES
    - Tier 1 count by response choice
    - Tier 2 count + trigger types
    - Net sentiment delta from pressers
    Pull from press_event + tier2_press_event."""
    # Get team ID
    coach = conn.execute("""
        SELECT ct.current_team_id
        FROM coach_career ct
        WHERE ct.id = ?
    """, (coach_id,)).fetchone()

    if not coach or not coach['current_team_id']:
        return ""

    team_id = coach['current_team_id']

    # Tier 1 events
    tier1_events = conn.execute("""
        SELECT pe.selected_response
        FROM press_event pe
        WHERE pe.season_year = ? AND pe.team_id = ? AND pe.resolved_at IS NOT NULL
    """, (season_year, team_id)).fetchall()

    # Tier 2 events
    tier2_events = conn.execute("""
        SELECT t2.trigger_type
        FROM tier2_press_event t2
        WHERE t2.season_year = ? AND t2.team_id = ? AND t2.resolved_at IS NOT NULL
    """, (season_year, team_id)).fetchall()

    if not tier1_events and not tier2_events:
        return ""

    lines = [bold("PRESS CONFERENCES", use_color), DISPLAY_BORDER_LIGHT]

    # Tier 1 breakdown
    if tier1_events:
        response_counts = {}
        for event in tier1_events:
            resp = event['selected_response'] or 'deflect'
            response_counts[resp] = response_counts.get(resp, 0) + 1

        tier1_total = len(tier1_events)
        lines.append(f"  Weekly press conferences: {tier1_total}")

        for resp_type in ['deflect', 'accountable', 'confrontational']:
            count = response_counts.get(resp_type, 0)
            if count > 0:
                lines.append(f"    {resp_type.capitalize()}: {count}")

    # Tier 2 breakdown
    if tier2_events:
        tier2_total = len(tier2_events)
        lines.append(f"  Dramatic pressers: {tier2_total}")

        trigger_counts = {}
        for event in tier2_events:
            trigger = event['trigger_type']
            trigger_counts[trigger] = trigger_counts.get(trigger, 0) + 1

        for trigger, count in sorted(trigger_counts.items()):
            trigger_display = trigger.replace('_', ' ').title()
            lines.append(f"    {trigger_display}: {count}")

    # Net sentiment delta (read from owner_sentiment.presser_delta)
    sentiment = get_owner_sentiment(conn, team_id, season_year)
    if sentiment:
        presser_delta = sentiment['presser_delta']
        if presser_delta != 0:
            if presser_delta > 0:
                delta_str = green(f"+{presser_delta}", use_color)
            else:
                delta_str = red(f"{presser_delta}", use_color)
            lines.append(f"  Net sentiment impact: {delta_str}")

    return '\n'.join(lines)


SECTION_RENDERERS = {
    'header': render_header,
    'outcome': render_outcome,
    'narrative': render_narrative,
    'owner_relationship': render_owner_relationship,
    'legacy_update': render_legacy_update,
    'peer_rank': render_peer_rank,
    'records_broken': render_records_broken,
    'press_summary': render_press_summary,
}
